In [189]:
import pandas as pd
import numpy as np

In [194]:
auto_price = pd.read_csv(r'C:\Users\steph\bepec\Machine Learning\Stream Lit\automobile_pricingLlinearRegression\data\Automobile price data _Raw_.csv', na_values="?")

In [195]:
auto_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    float64
 22  peak-rpm           203 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.8+ KB

In [196]:
auto_price.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [197]:
obj_auto_price = auto_price.select_dtypes(include="object").copy()

In [198]:
obj_auto_price.head(5)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,engine-type,num-of-cylinders,fuel-system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi

In [199]:
obj_auto_price[obj_auto_price.isnull().any(axis=1)]

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,engine-type,num-of-cylinders,fuel-system
27,dodge,gas,turbo,NaN,sedan,fwd,front,ohc,four,mpfi
63,mazda,diesel,std,NaN,sedan,fwd,front,ohc,four,idi

In [200]:
obj_auto_price['num-of-doors'].value_counts()

four    114
two      89
Name: num-of-doors, dtype: int64

In [202]:
obj_auto_price = obj_auto_price.fillna({"num-of-doors":"four"})

In [203]:
obj_auto_price['num-of-cylinders'].value_counts()

four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: num-of-cylinders, dtype: int64

In [204]:
cleanup_nums = {"num-of-doors":{"four":4, "two":2},
               "num-of-cylinders":{"four":4,"six":6,"five":5,"eight":8,"two":2,"three":3,"twelve":12}}

In [205]:
obj_auto_price = obj_auto_price.replace(cleanup_nums)

In [206]:
obj_auto_price.head(5)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,engine-type,num-of-cylinders,fuel-system
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi

In [207]:
obj_auto_price.dtypes

make                object
fuel-type           object
aspiration          object
num-of-doors         int64
body-style          object
drive-wheels        object
engine-location     object
engine-type         object
num-of-cylinders     int64
fuel-system         object
dtype: object

In [208]:
obj_auto_price["body-style"]  = obj_auto_price["body-style"].astype('category')

In [210]:
obj_auto_price["body-style"].dtype

CategoricalDtype(categories=['convertible', 'hardtop', 'hatchback', 'sedan', 'wagon'], ordered=False)

In [211]:
obj_auto_price["body-style-cat"] = obj_auto_price["body-style"].cat.codes

In [213]:
obj_auto_price.head(10)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,engine-type,num-of-cylinders,fuel-system,body-style-cat
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi,2
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi,3
5,audi,gas,std,2,sedan,fwd,front,ohc,5,mpfi,3
6,audi,gas,std,4,sedan,fwd,front,ohc,5,mpfi,3
7,audi,gas,std,4,wagon,fwd,front,ohc,5,mpfi,4
8,audi,gas,turbo,4,sedan,fwd,front,ohc,5,mpfi,3
9,audi,gas,turbo,2,hatchback,4wd,front,ohc,5,mpfi,2

In [235]:
pd.get_dummies(obj_auto_price, columns=["drive-wheels"]).head(10)

,make,fuel-type,aspiration,num-of-doors,body-style,engine-location,engine-type,num-of-cylinders,fuel-system,body-style-cat,OHC_code,drive-wheels_4wd,drive-wheels_fwd,drive-wheels_rwd
0,alfa-romero,gas,std,2,convertible,front,dohc,4,mpfi,0,1,0,0,1
1,alfa-romero,gas,std,2,convertible,front,dohc,4,mpfi,0,1,0,0,1
2,alfa-romero,gas,std,2,hatchback,front,ohcv,6,mpfi,2,1,0,0,1
3,audi,gas,std,4,sedan,front,ohc,4,mpfi,3,1,0,1,0
4,audi,gas,std,4,sedan,front,ohc,5,mpfi,3,1,1,0,0
5,audi,gas,std,2,sedan,front,ohc,5,mpfi,3,1,0,1,0
6,audi,gas,std,4,sedan,front,ohc,5,mpfi,3,1,0,1,0
7,audi,gas,std,4,wagon,front,ohc,5,mpfi,4,1,0,1,0
8,audi,gas,turbo,4,sedan,front,ohc,5,mpfi,3,1,0,1,0
9,audi,gas,turbo,2,hatchback,front,ohc,5,mpfi,2,1,1,0,0

In [236]:
pd.get_dummies(obj_auto_price, columns=["body-style","drive-wheels"], prefix=["body","drive"]).head(10)

,make,fuel-type,aspiration,num-of-doors,engine-location,engine-type,num-of-cylinders,fuel-system,body-style-cat,OHC_code,body_convertible,body_hardtop,body_hatchback,body_sedan,body_wagon,drive_4wd,drive_fwd,drive_rwd
0,alfa-romero,gas,std,2,front,dohc,4,mpfi,0,1,1,0,0,0,0,0,0,1
1,alfa-romero,gas,std,2,front,dohc,4,mpfi,0,1,1,0,0,0,0,0,0,1
2,alfa-romero,gas,std,2,front,ohcv,6,mpfi,2,1,0,0,1,0,0,0,0,1
3,audi,gas,std,4,front,ohc,4,mpfi,3,1,0,0,0,1,0,0,1,0
4,audi,gas,std,4,front,ohc,5,mpfi,3,1,0,0,0,1,0,1,0,0
5,audi,gas,std,2,front,ohc,5,mpfi,3,1,0,0,0,1,0,0,1,0
6,audi,gas,std,4,front,ohc,5,mpfi,3,1,0,0,0,1,0,0,1,0
7,audi,gas,std,4,front,ohc,5,mpfi,4,1,0,0,0,0,1,0,1,0
8,audi,gas,turbo,4,front,ohc,5,mpfi,3,1,0,0,0,1,0,0,1,0
9,audi,gas,turbo,2,front,ohc,5,mpfi,2,1,0,0,1,0,0,1,0,0

In [237]:
obj_auto_price["engine-type"].value_counts()

ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: engine-type, dtype: int64

In [238]:
obj_auto_price["engine-type"].value_counts()

ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: engine-type, dtype: int64

In [239]:
obj_auto_price["OHC_code"] = np.where(obj_auto_price["engine-type"].str.contains("ohc"),1,0)

In [240]:
obj_auto_price[['make', 'engine-type', 'OHC_code']].head(5)

          make engine-type  OHC_code
0  alfa-romero        dohc         1
1  alfa-romero        dohc         1
2  alfa-romero        ohcv         1
3         audi         ohc         1
4         audi         ohc         1

In [241]:
obj_auto_price.head(5)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,engine-type,num-of-cylinders,fuel-system,body-style-cat,OHC_code
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0,1
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0,1
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi,2,1
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3,1
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi,3,1